# $OpenBSD: Makefile,v 1.3 2002/06/08 06:03:09 pvalchev Exp $
COMMENT=	"Rogue like adventure game"

VERSION=	3.2
DISTNAME=	wanderer-${VERSION}
NEED_VERSION=	3.2

CATEGORIES=	games

HOMEPAGE=	http://www.surferz.net/~marina/

MAINTAINER=	Marina Brown <marina@surferz.net>

# Freely distributable With Credits - do not delete screens
PERMIT_PACKAGE_CDROM=   Yes
PERMIT_PACKAGE_FTP=     Yes
PERMIT_DISTFILES_CDROM= Yes
PERMIT_DISTFILES_FTP=   Yes

MASTER_SITES=	${HOMEPAGE}

.include <bsd.port.mk>
